@resource = kindergartens
@host = localhost
@port = 55555
@id =  kinder1
@queryStrings = partial-matching-target=mogucare1

### データの追加

POST http://{{host}}:{{port}}/{{resource}}/ HTTP/1.1
content-type: application/json

{
  "name": "sample"
}

### 画像の追加

POST http://{{host}}:{{port}}/{{resource}}/image?kindergarten-id={{id}} HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="sample.png"
Content-Type: image/png

< ./sample.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 全データ取得

GET http://{{host}}:{{port}}/{{resource}}/ HTTP/1.1

### 特定idのデータ取得

GET http://{{host}}:{{port}}/{{resource}}/{{id}} HTTP/1.1

### クエリパラメータを使った特定データ取得の取得

GET http://{{host}}:{{port}}/{{resource}}?{{queryStrings}} HTTP/1.1

### 特定idのデータを変更

PUT http://{{host}}:{{port}}/{{resource}}/{{id}} HTTP/1.1
content-type: application/json

{
  "changed": "changed"
}

### 特定idのデータを削除

DELETE  http://{{host}}:{{port}}/{{resource}}/{{id}} HTTP/1.1
